- backend/.eslintrc.js
- backend/.gitignore
- backend/.prettierrc
- backend/README.md
- backend/nest-cli.json
- backend/package-lock.json
- backend/package.json
- backend/src/app.controller.ts
- backend/src/app.module.ts
- backend/src/app.service.ts
- backend/src/configs/typeorm.config.ts
- backend/src/main.ts
- backend/tsconfig.build.json
- backend/tsconfig.json
#8 개발환경 세팅
- Nestjs 설치 및 적용
- TypeORM 적용
- Eslint + Prettier 적용
- Postgresql 연동
- 환경 변수 설정
---
- 없음
> [1주차] 백엔드 개발환경 세팅

- frontend/package-lock.json
- frontend/package.json
- frontend/src/component/Background/background.styled.ts
- frontend/src/component/Background/index.tsx
- frontend/src/component/Modal/index.tsx
- frontend/src/component/Modal/modal.styled.ts
- frontend/src/component/Oauth/index.tsx
- frontend/src/component/Oauth/oauth.styled.ts
- frontend/src/component/Setting/index.tsx
- frontend/src/component/Setting/setting.styled.ts
- frontend/src/global.ts
- frontend/src/page/Main/index.tsx
- frontend/src/page/Signin/index.tsx
- frontend/src/page/Signup/index.tsx
- frontend/tsconfig.json
- frontend/vite.config.ts
#13
-  component, page 폴더 분리
- main page 관련 component, page 생성
- 특이사항1
- 특이사항2
> main page 구조 세팅

- frontend/src/styles/mixin.styled.ts
center mixin 생성
- 중앙정렬할 수 있는 mixin 생성
- 사용법
```css
import { center } from '/src/styles/mixin.styled';
const test = css`
${center}
`;
```
> center mixin 생성

- frontend/src/component/Button/button.styled.ts
- frontend/src/component/Button/index.tsx
- frontend/src/component/MainContent/index.tsx
- frontend/src/component/MainContent/mainContent.styled.ts
- frontend/src/page/Main/index.tsx
> Main page 마크업

- frontend/src/component/Background/index.tsx
- frontend/src/component/Modal/index.tsx
- frontend/src/component/Modal/modal.styled.ts
- frontend/src/page/Signup/index.tsx
- frontend/src/page/Signup/signup.styled.ts
- frontend/src/types/types.ts
#17
- children type 분리 및 수정
- modal 중앙 정렬
- 특이사항1
- 특이사항2
> children type 분리 및 modal css 수정

- backend/src/user/user.controller.ts
소셜에 따른 로그인 페이지 redirection 제공 (Naver)
#4 #5 
- `localhost:3333/user/login?social=naver` 로 naver 로그인 가능
- 없음
> 소셜에 따른 로그인 페이지 redirection 제공

- backend/src/main.ts
- #27 
- backend main.ts에서 `app.enableCors()` 처리
- 없음
> CORS 에러 해결

- backend/src/main.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.service.ts
구글 로그인 구현 (1/2)
- #4
- #5 
- google OAuth를 통해 유저 accessToken 받기
- google Profile 조회 API를 통해 유저 정보 받기
- 받은 user id로 기존 유저인지 식별후 redirect 처리
- 없음
> [feat] #4 #5 구글 로그인 구현 (1/2)

- backend/src/user/user.controller.ts
- backend/src/user/user.service.ts
- frontend/package-lock.json
[대규모 리팩토링] 소셜 로그인 공통 로직 추상화
#4 #5 
- 공통 로직 전부 추상화하여 사용
- 소셜 사이트에 Profile 조회하는 부분 Return 형식 지정 
- 없음
> [refactor] #4 #5 소셜 로그인 서버 로직 추상화

- frontend/src/component/Game/Phaser/Player/player.ts
- frontend/src/component/Game/game.ts
- frontend/src/component/Game/util.ts
#10
- 기존 temp로 구분했던 구르기 동작을 speed만 바꿔줄 수 있도록 변경
- Phaser.GameObjects.Sprite를 상속받는 Player 객체 생성 및 적용
> player 로직 분리 및 key event 수정

- backend/src/auth/auth.service.ts
- backend/src/auth/dto/user-data.dto.ts
- backend/src/auth/entity/user.entity.ts
- backend/src/auth/jwt-auth.strategy.ts
- backend/src/auth/pipes/social-platform.pipe.ts
- backend/src/auth/user.controller.ts
- backend/src/auth/user.service.ts
유저 시스템 API들 완성 및 코드 정리
- #4 
- #5 
- #7 
- #9 
- 코드 정리 및 SocialPlatform Pipe 추가
- 회원가입 API 수정 및 pipe 추가
- 로그아웃 API 완성
- 회원탈퇴 API 완성
- signup API 보낼 시, 데이터 유의
```
// body 형식
{
"signupData": {
"nickname" : "stouter",
"characterName": "lion"
}
}
```
- nickname 은 한글, 영어, 숫자, 공백 가능. 4글자~12글자
> 유저 시스템 완성 및 코드 퀄리티 향상

- frontend/src/component/Game/Phaser/Player/player.ts
- frontend/src/component/Game/game.ts
- frontend/src/component/Snow/index.tsx
- frontend/src/component/Snow/snow.styled.ts
#6 #10 
- 구르기 이미지 수정 및 속도 변경
- 눈 이미지 개수에 맞는 위치 조정
- 
> 구르기 및 눈 내리기 리팩토링

- backend/src/auth/user.controller.ts
Authorization API 추가
#4 
#5 
- GET /user/auth 으로 criticalGuard 통과하는 지 확인
- 없음
> Authorization API 추가

- frontend/src/component/Sidebar/index.tsx
- frontend/src/component/Sidebar/sidebar.styled.ts
#42  
- 보다 시맨틱하게 변경
- z-index 추가하여 사이드바가 눈보다 상위로 올라오도록 수정
> 태그 변경 및 마크업 수정

- backend/src/auth/user.controller.ts
- backend/src/auth/user.service.ts
- backend/src/board/board.controller.ts
- backend/src/board/board.module.ts
- backend/src/board/board.service.ts
- backend/src/board/dto/article-data.dto.ts
- backend/src/board/entity/board.entity.ts
- backend/src/board/pipes/category.pipe.ts
- backend/src/friendship/friendship.controller.ts
- backend/src/friendship/friendship.service.ts
#44 
#48 
#50 
#52 
#66 
- `GET` `/board` : 내가 팔로우한 유저들의 게시글 불러오기 (최신순)
- `POST` `/board` : 게시글 작성 요청
- API 응답 구체화 및 통일 : 자세한 내용은 wiki
- followingList 나 articleList API 응답 간소화
- 없음
> SleepyBoard 관련 API 생성 및 응답 구체화

- frontend/src/component/Game/Phaser/Player/myPlayer.ts
- frontend/src/component/Game/Phaser/Player/player.ts
- frontend/src/component/Game/util.ts
- frontend/src/component/Setting/index.tsx
#80
- myPlayer, otherPlayer 분리
- changePosition 함수 분리
- 특이사항1
- 특이사항2
> Player class 분리

- frontend/src/component/Game/game.ts
- frontend/src/component/Game/gameConfig.ts
- frontend/src/component/Sidebar/Friends/friends.styled.ts
- #82 
- fps 고정
- 경로 오타 수정
- sidebar 높이 수정
> 에러 해결 및 스타일 수정

- backend/src/adapters/socket-io.adapter.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/component/Game/game.ts
- frontend/src/page/Main/index.tsx
- frontend/src/page/Town/index.tsx
- frontend/src/store/atom/socket.ts
- #51 
- 소켓 recoil atom 생성
- 소켓 연결
- 노래 너무 시끄러워서 잠시 주석처리 해뒀습니다.
- 현재 recoil 내부에 socket 저장이 안 되어 해당 문제 수정 중에 있습니다. 임시로 변수에 저장해두었으니, 참고하여 주시기 바랍니다.
- getcookie 함수 분리할 위치 고민해봐요 (외 다른 util 함수들도 분리할 수 있도록)
> frontend 소켓 연결 

- backend/package-lock.json
- backend/package.json
- backend/src/app.module.ts
- backend/src/auth/entity/user.entity.ts
- backend/src/chat/chat.controller.ts
- backend/src/chat/chat.module.ts
- backend/src/chat/chat.service.ts
- backend/src/chat/entity/chat-mark.entity.ts
- backend/src/chat/entity/chat-room.entity.ts
- backend/src/chat/entity/chat.entity.ts
- backend/src/socket/socket.gateway.ts
- #3 
- 채팅방
- 채팅내역
- 채팅열람 내역
- 없음
> 채팅방 생성, 채팅 기록, 열람내역 저장

- backend/src/chat/chat.controller.ts
- backend/src/chat/chat.service.ts
- backend/src/chat/entity/chat-mark.entity.ts
- backend/src/friendship/friendship.service.ts
- backend/src/socket/socket.gateway.ts
- frontend/package-lock.json
채팅방 목록 및 채팅 내용 불러오기 API
- #3 
소켓 수정
- #51 
- 채팅방 목록 불러오기 API 생성
- 채팅방 내용 불러오기 API 생성
- socket에서의 의도치 않은 disconnecting 감지하는 로직 추가
- API 및 socket 명세 오늘 내로 만들어드리겠습니다.
> 채팅방 목록 및 채팅 내용 불러오기 API

- backend/src/auth/dto/user-data.dto.ts
- backend/src/auth/entity/user.entity.ts
- backend/src/chat/entity/chat.entity.ts
DB nickname, characterName 자료형 및 검증 로직 수정
- #93 
- nickname, characterName : varchar(16)으로 변경
- padding 문제 해결
- nickname 2~16글자 가능
- 프론트에서 nickname 입력할 때, 2~16 가능하도록 변경해주세요~~~
> DB nickname, characterName 자료형 및 검증 로직 수정

- README.md
- backend/src/chat/chat.service.ts
- backend/src/socket/socket.gateway.ts
Socket 명세 구체화 및 Wiki 작성
- #51
- #3 
- socket 반환 data 구조 변경
- Wiki에 socket 명세 작성 완료
- 최상위 README.md 수정
- 자세한 건 github Wiki 의 socket 명세를 봐주세요~
> Socket 명세 구체화 및 Wiki 작성

- backend/package-lock.json
- backend/src/board/board.controller.ts
- backend/src/board/board.service.ts
- backend/src/board/entity/board.entity.ts
- backend/src/socket/socket.gateway.ts
> 게시글 조회 필터, 유저데이터 변경 broadcast

- frontend/src/component/Game/game.ts
#108 
- 닉네임 지워주기
- socket 변경에 따른 코드 수정(캐릭터 지워주기)
- 특이사항1
- 특이사항2
> 유저가 떠났을때 닉네임 지워주기

- frontend/src/Router.tsx
- frontend/src/component/Chat/ChatContent.tsx
- frontend/src/component/Chat/ChatMessage.tsx
- frontend/src/component/Chat/Input.tsx
- frontend/src/component/Chat/index.tsx
- frontend/src/component/Chat/util.ts
- frontend/src/component/Sidebar/Chat/ChatList.tsx
- frontend/src/component/Sidebar/Friends/callingList.tsx
- frontend/src/component/Sidebar/Friends/friendItem.tsx
- frontend/src/component/Sidebar/Friends/friendList.tsx
- frontend/src/component/Sidebar/Friends/friends.styled.ts
- frontend/src/component/Sidebar/Friends/friends.ts
- frontend/src/component/Sidebar/Friends/search.tsx
- frontend/src/page/Main/index.tsx
- frontend/src/store/atom/friends.ts
- #3
- #118 
- 소켓 통신
- Chat 컴포넌트의 지역 상태로 채팅 관리
- 상태(배열) 초기화 되는 문제 해결(#118 )
- 시간 계산 함수
- 특이사항1
- 특이사항2
> 소켓 통신을 통한 전체 채팅 구현

- backend/package-lock.json
- backend/src/auth/user.service.ts
- backend/src/friendship/friendship.controller.ts
시작 닉네임으로 유저 목록 검색
- #123 
- `시작 닉네임`으로 유저 목록 검색 API 생성
- `GET` `/friendship/{시작닉네임}`
- 배열 형식 반환
- `GET` `/friendship/{시작닉네임}` 으로 요청
- `GET` `/friendship/{시작닉네임}`
- 성공 (200) - 항상 배열 형식으로 반환
```
[ // 해당 이름으로 시작하는 유저 2
{
"id": "1NJfqr-aPPEfIJPIvFNd6OzG8qFqTUSRNbT7bxM24R0",
"nickname": "jongbin",
"characterName": "curlyhair",
"social": "naver",
"created_at": "2022-11-29",
"deleted": false
},
{
"id": "Z-NVwpPpbw7oOjHEn-CYEZ8V9nU3P9IIChz_9PuuVak",
"nickname": "j002",
"characterName": "mophair",
"social": "naver",
"created_at": "2022-11-29",
"deleted": false
}
]
```
```
// 해당 이름으로 시작하는 유저 x
[]
```
- 실패 (404)
```
{ // Query 오류
"statusCode": 404,
"message": "해당 nickname으로 시작하는 유저들이 없습니다.",
"error": "Not Found"
}
```
```
{ // 토큰 x
"statusCode": 401,
"message": "Unauthorized"
} …
```
> 시작 닉네임으로 유저 목록 검색

- frontend/src/Router.tsx
- frontend/src/component/Sidebar/Friends/friendList.tsx
- frontend/src/component/Sidebar/Friends/friends.styled.ts
- frontend/src/guard.tsx
- frontend/src/page/Main/index.tsx
- frontend/src/page/Town/index.tsx
- frontend/src/store/atom/friends.ts
- #121 
- #66 
- 새로고침 될 때나, 페이지 이동 시, 필수 요소를 guard로 확인
- 친구가 없을 때, 리스트 대신 보여줄 수 있는 컴포넌트 구현
> frontend guard 설정 및 친구 목록 수정

- frontend/src/component/Game/index.tsx
- #126 
- 뒤로가기 후 재실행시 움직이지 않는 에러
- 추가적인 에러, 버그 말씀해주세용
> 뒤로가기 후 재실행시 움직이지 않는 에러

- backend/src/auth/user.controller.ts
- backend/src/auth/user.service.ts
- backend/src/friendship/friendship.controller.ts
카카오 소셜 로그인 문제 해결
- #142 
자기 자신 친구 추가 불가능 하도록 수정
- #141 
- 카카오 소셜 로그인 문제 해결
- 자기 자신 친구 추가 불가능 하도록 수정
- 이제 카카오톡 회원가입 됩니다!
> 카카오 소셜 로그인 문제 및 사소한 이슈 해결

- backend/src/achievement/achievement.controller.ts
- backend/src/achievement/achievement.module.ts
- backend/src/achievement/achievement.service.ts
- backend/src/achievement/entity/walk.entity.ts
월별 걸음 수 랭킹 불러오기
- #139 
- 월별 걸음 수 랭킹 불러오기
- `GET` `/achievement/walk?year={yyyy}&month={m}&range={’all’ || ‘friend’}`
- 쿠키에 `accessToken` 필요
- 성공 (200)
```
[ // GET /achievement/walk?year=2022&month=12&range=all
{
"userid": "9B8X7YWtA0XlNTBzCItRGmLlUKBYkHdshMPqtsE7sWE",
"year": 2022,
"month": 12,
"walkcount": "2525",
"nickname": "ktmihs"
},
{
"userid": "k2526688659",
"year": 2022,
"month": 12,
"walkcount": "22",
"nickname": "j00002"
},
{
"userid": "1NJfqr-aPPEfIJPIvFNd6OzG8qFqTUSRNbT7bxM24R0",
"year": 2022,
"month": 12,
"walkcount": "10",
"nickname": "jongbin"
}
]
```
- 성공 (200)
```
[ // GET /achievement/walk?year=2022&month=12&range=friend
{
"userid": "k2526688659",
"year": 2022,
"month": 12,
"walkcount": "22",
"nickname": "j00002"
},
{
"userid": …
```
> 월별 걸음 수 랭킹 불러오기

- frontend/src/component/Background/index.tsx
- frontend/src/component/Game/game.ts
- frontend/src/component/Game/index.tsx
- frontend/src/component/MainContent/mainContent.styled.ts
- frontend/src/component/Oauth/index.tsx
- frontend/src/component/Oauth/oauth.styled.ts
- frontend/src/component/Sidebar/Friends/friendItem.tsx
- frontend/src/component/SigninContent/index.tsx
#155 
- 빌드 과정에서 에러가 나 호출 방법을 변경해줌
> [fix] #155 정적 이미지 호출 방법 수정

- frontend/src/component/Sidebar/Chat/Chatting.tsx
- #3 
- 채팅 메시지 없어 index를 찾을 수 없으면, 0으로 설정
> 채팅 메시지 없을 때 index error 수정

- backend/package-lock.json
- frontend/src/component/Game/Phaser/Player/myPlayer.ts
- frontend/src/component/Game/Phaser/Player/player.ts
- frontend/src/component/Game/util.ts
- frontend/src/store/atom/socket.ts
- #137
- #49 
- 다른 유저에서도 적용되어 적용이 안 되도록 외부로 이동
> 페이저 움직임 수정 및 소켓 주소 변경

- .github/workflows/backend_deploy.yml
- .github/workflows/frontend_deploy.yml
- backend/src/auth/user.controller.ts
- backend/src/socket/socket.gateway.ts
- #4 
- #49 
- #51 
- #164 
- #165 
- 통화 정책 관련해서 논의 필요
> 카카오계정 이슈, 소켓 유저상태 및 통화 상태관리, 배포 자동화

- frontend/src/component/Game/Phaser/Player/myPlayer.ts
> 순간 이동 에러 수정

- backend/src/board/board.service.ts
- backend/src/socket/socket.gateway.ts
통화 관련 socket 이벤트 완벽 구현
- #165
좋아요한 게시글 조회 시 like 컬럼 추가
- #50 
- 통화 관련 정책 변경에 따른 이벤트 수정
- 형진&성준의 치밀한 Test Case 통과
- 조만간 socket 명세에 적겠습니다~
> 통화 관련 socket 이벤트 완벽 구현, 좋아요한 게시글 조회 시 like 컬럼 추가

- backend/src/socket/socket.gateway.ts
- frontend/src/component/Call/call.styled.ts
- frontend/src/component/Call/index.tsx
- frontend/src/component/Call/video.tsx
> webRTC 1:1 화상 / 음성 채팅

- frontend/src/component/Call/index.tsx
- frontend/src/component/Sidebar/Friends/friendList.tsx
> 유저 상태 로직 수정

- backend/src/app.module.ts
- backend/src/socket/socket.gateway.ts
- frontend/src/component/Call/call.styled.ts
- frontend/src/component/Call/callingItem.tsx
- frontend/src/component/Call/video.tsx
WebRTC를 통한 1:1 통화 기능 구현
- #136 
- #148 
- 프론트 분들이 시급합니다!
> WebRTC를 통한 1:1 통화 기능 구현

- frontend/src/component/Call/callingItem.tsx
- frontend/src/component/Call/config.ts
- frontend/src/component/Call/remoteVideo.tsx
- frontend/src/component/Call/video.tsx
- frontend/src/component/Call/vvv.tsx
- frontend/src/component/Game/Scene/sprint.ts
- frontend/src/component/Sidebar/Friends/callingList.tsx
- frontend/src/store/atom/callingList.ts
반쪽짜리 N:M WebRTC 구현
- #189 
- 최대 4명 까지 가능
- 전화는 한명만 걸자
- 리팩토링 필수
> [feat] #189 반쪽짜리 N:M WebRTC 구현

- frontend/src/component/Call/call.styled.ts
- frontend/src/component/Call/callingItem.tsx
- frontend/src/component/Call/index.tsx
- frontend/src/component/Call/video.tsx
- frontend/src/component/MiniGame/miniGame.styled.ts
- frontend/src/component/Sidebar/Friends/callingList.tsx
- frontend/src/component/Sidebar/Friends/friendList.tsx
> webRTC 연결 시, 실시간 상태 변경

- frontend/src/component/Call/call.styled.ts
- frontend/src/component/Call/remoteVideo.tsx
- frontend/src/component/Call/video.tsx
- frontend/src/component/Chat/ChatMessage.tsx
- frontend/src/component/Game/Phaser/Player/myPlayer.ts
- frontend/src/component/Game/Scene/town.ts
- frontend/src/component/Info/Users.tsx
- frontend/src/component/Info/Walk.tsx
- frontend/src/component/Sidebar/Chat/ChatList.tsx
- frontend/src/component/Sidebar/Chat/Chatting.tsx
- frontend/src/component/Sidebar/Friends/callingList.tsx
- frontend/src/component/Sidebar/Friends/friendList.tsx
- 소켓 removeListener 버그 수정
- 특이사항1
- 특이사항2
> 소켓 removeListener 버그 수정

- backend/src/board/article.enum.ts
- backend/src/socket/socket.gateway.ts
- frontend/src/component/Call/call.styled.ts
- frontend/src/component/Call/callingItem.tsx
- frontend/src/component/Call/index.tsx
- frontend/src/component/Call/remoteVideo.tsx
- frontend/src/component/Call/video.tsx
- frontend/src/component/MiniGame/FriendMode.tsx
- frontend/src/component/Sidebar/Friends/callingList.tsx
- frontend/src/component/Sidebar/Friends/friendList.tsx
- frontend/src/component/Sidebar/index.tsx
- frontend/src/store/atom/deviceSetting.ts
- frontend/src/types/types.ts
WebRTC를 통한 화상, 음성 통화 기능 완벽 구현
- #189 
- 디자인 수정
- 통화 나가기 버튼 수정
- 없음
> [feat] #189 WebRTC를 통한 화상, 음성 통화 기능 완벽 구현

- frontend/src/component/Game/Scene/maze.ts
- frontend/src/component/Game/Scene/running.ts
- frontend/src/component/Sidebar/sidebar.styled.ts
- #185 
- 미니게임 에러 수정
- 사이드바 스타일 수정
- 특이사항1
- 특이사항2
> 미니게임 에러 수정

- frontend/src/component/Chat/ChatMessage.tsx
- #3 
- 전체 채팅 스토리지 데이터 가져오기
- 특이사항1
- 특이사항2
> 전체 채팅 스토리지 데이터 가져오기

- frontend/src/component/Sidebar/Chat/ChatList.tsx
- frontend/src/component/Sidebar/Chat/ChatMessage.tsx
- frontend/src/component/Sidebar/Chat/Chatting.tsx
- frontend/src/component/Sidebar/Chat/SeparateTimeLine.tsx
- frontend/src/component/Sidebar/Chat/util.ts
-#3
- 채팅 시간 표시 에러 수정
- 채팅 메세지 react key 설정
- 특이사항1
- 특이사항2
> 채팅 시간 표시 에러 및 key 설정
